---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - gdb
      - golang
      - git
      - pandoc
      - build-essential
      - libpcap-dev
      - libusb-1.0-0-dev
      - libnetfilter-queue-dev
      - libglib2.0-dev
      - wireless-tools
      - aircrack-ng
      - tshark
      - reaver
      - bully
      - cowpatty
      - gcc
      - make
      - cewl
      - dos2unix
      - htop
      - open-iscsi
      - nfs-common
      - rlwrap
      - crunch
      - windows-binaries
      - powershell
      - jq
      - xdotool
      - eyewitness
      - neovim
      - p7zip-full
      - cifs-utils
      - dnsmasq
      - dnsutils
      - net-tools
      - tmux
      - build-essential
      - ldap-utils
      - smbclient
      - chromium
      - chromium-common
      - dos2unix
      - apt-transport-https
      - masscan
      - sshuttle
      - flameshot
      - openssl
      - neo4j
      - mingw-w64
      - dnsrecon
      - jsbeautifier
      
    state: latest
  become: true
  become_method: sudo
