---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - aircrack-ng
      - amass
      - apt-transport-https
      - build-essential
      - build-essential
      - bully
      - cewl
      - chromium
      - chromium-common
      - cifs-utils
      - cowpatty
      - crunch
      - dnsmasq
      - dnsrecon
      - dnsutils
      - dos2unix
      - dos2unix
      - exiftool
      - eyewitness
      - flameshot
      - flameshot
      - gcc
      - gdb
      - git
      - golang
      - htop
      - jq
      - jq
      - jsbeautifier
      - ldap-utils
      - libglib2.0-dev
      - libnetfilter-queue-dev
      - libpcap-dev
      - libusb-1.0-0-dev
      - make
      - masscan
      - mingw-w64
      - neo4j
      - neovim
      - net-tools
      - nfs-common
      - ntpdate
      - open-iscsi
      - openssl
      - p7zip-full
      - pandoc
      - pipx
      - powershell
      - reaver
      - responder
      - rlwrap
      - smbclient
      - sshuttle
      - tmux
      - tshark
      - windows-binaries
      - wireless-tools
      - xdotoo
      - ffmpeg
      - wpscan
      
    state: latest
  become: true
  become_method: sudo
