---
- name: "Installing Kerbrute"
  shell: go install github.com/ropnop/kerbrute@master

- name: "Installing ffuf"
  shell: go install -v github.com/ffuf/ffuf@latest

- name: "Installing Byp4xx"
  shell: go install github.com/lobuhi/byp4xx@latest

- name: "Installing nuclei"
  shell: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

- name: "Installing nmap-formatter"
  shell: go install github.com/vdjagilev/nmap-formatter@latest

- name: "Installing subfinder"
  shell: go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest

- name: "Installing Dependencies to Naabu"
  package: 
    name: 
      - libpcap-dev
  become: true
  become_method: sudo
  
- name: "Installing Naabu"
  shell: go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest

- name: "Installing httpx"
  shell: go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest