---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/mpgn/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }

- name: "Installing tools that need virtual environments"
  ansible.builtin.pip:
    name: "{{ item.name }}"
    virtualenv: "{{(lookup('env','HOME'))}}/opt/{{ item.name}}"
  loop:
    - { name: 'lsassy'}

- name: "Installing python tools that does NOT need virtual environments"
  ansible.builtin.pip:
    name: arsenal-cli
