---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: gantsign.visual-studio-code
    - role: "roles/customize-looks"
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode


