---
- name: "Copy Bashrc"
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}"

- name: "Add color to terminal"
  copy:
    src: "{{ role_path }}/files/color.theme"
    dest: "/usr/share/xfce4/terminal/colorschemes/color.theme"

- name: "Add colorSSSSSSS to terminal"
  become: true
  become_user: root
  become_method: sudo
  shell: whoami

- name: "change user shell to bash"
  become: true
  become_method: sudo
  user:
    name: "user"
    shell: /bin/bash