---
- name: Downloading Burp Suite Pro
  ansible.builtin.get_url:
    # TODO: Find a cool way to make this take the latest version of Burp Suite Pro.
    url: https://portswigger.net/burp/releases/download?product=pro&version=2023.8&type=Linux
    dest: /tmp/burpsuitePro.sh

- name: Installing Burp Suite Pro as current user
  shell: bash /tmp/burpsuitePro.sh -q "{{ role_path }}/files/response.varfile"
  async: 60
  poll: 10

- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory

- name: Download jar files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"

- name: Copy BurpSuite Pro Config
  template:
    src: "templates/UserConfigPro.json.j2"
    dest: "/home/{{ ansible_user_id }}/.BurpSuite/UserConfigPro.json"

- name: Prompt to make the user remember to install Burp extensions
  ansible.builtin.pause:
    prompt: "Dont forget to install license and extensions to Burp after this is done!"
    seconds: 30

